name: msedit
base: core24
version: '1.2.1'
summary: Edit is an MS-DOS inspired text editor from Microsoft
description: |
  Edit pays homage to the classic MS-DOS Editor, but with a modern interface and input controls similar to VS Code. Learn more at https://github.com/microsoft/edit

  Disclaimer: This is an unofficial Snap and it is not endorsed by nor affiliated officially with Microsoft Corporation.

grade: stable
confinement: strict

apps:
  msedit:
    command: bin/edit
    plugs:
      - home

parts:
  edit:
    source: https://github.com/microsoft/edit.git
    source-type: git
    plugin: rust
    build-packages:
      - build-essential
