.TH EDIT 1 "version 1.0" "May 2025"
.SH NAME
edit \- a simple text editor
.SH SYNOPSIS
edit [file]
.SH DESCRIPTION
edit is a simple text editor inspired by MS-DOS edit.
.SH EDITING
Edit is an interactive mode-less editor. Use Alt-F to access the menus.
.SH OPTIONS
Pass the name of the file to edit.
.SH SEE ALSO
https://github.com/microsoft/edit
.SH AUTHOR
Leonard Hecker
