[package]
name = "lsh-gen"
version = "0.0.0"

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
regex-syntax = { version = "0.8", default-features = false }
