[package]
name = "grapheme-table-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
indoc = "2.0"
pico-args = { version = "0.5", features = ["eq-separator"] }
rayon = "1.10"
roxmltree = { version = "0.20", default-features = false, features = ["std"] }
